package com.spring.model;
// Generated Mar 30, 2017 6:44:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="webtec"
)
public class Role  implements java.io.Serializable {


     private Integer roleId;
     private String name;
     private Set<Userdata> userdatas = new HashSet<Userdata>(0);

    public Role() {
    }

    public Role(String name, Set<Userdata> userdatas) {
       this.name = name;
       this.userdatas = userdatas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="role_Id", unique=true, nullable=false)
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
//    public Set<Userdata> getUserdatas() {
//        return this.userdatas;
//    }
//    
//    public void setUserdatas(Set<Userdata> userdatas) {
//        this.userdatas = userdatas;
//    }




}


