package com.spring.model;
// Generated Mar 30, 2017 6:44:03 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Userdata generated by hbm2java
 */
@Entity
@Table(name = "userdata", catalog = "webtec", uniqueConstraints = {
    @UniqueConstraint(columnNames = "userName"),
    @UniqueConstraint(columnNames = "email")}
)
public class Userdata implements java.io.Serializable {

    private Integer userId;
    private Role role;
    private String userName;
    private String password;
    private String firstName;
    private String lastName;
    private String age;
    private String email;
    private String instagramUsername;
    private String discription;
    private boolean allowEmailNotification;
    private String interest;
    private String profileImage;
    private Date createDate;

    public Userdata() {
    }

    public Userdata(Role role, String userName, String password, boolean allowEmailNotification) {
        this.role = role;
        this.userName = userName;
        this.password = password;
        this.allowEmailNotification = allowEmailNotification;
    }

    public Userdata(Role role, String userName, String password, String firstName, String lastName, String age, String email, String instagramUsername, String discription, boolean allowEmailNotification, String interest, String profileImage, Date createDate) {
        this.role = role;
        this.userName = userName;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.email = email;
        this.instagramUsername = instagramUsername;
        this.discription = discription;
        this.allowEmailNotification = allowEmailNotification;
        this.interest = interest;
        this.profileImage = profileImage;
        this.createDate = createDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "user_Id", unique = true, nullable = false)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "role_Id", nullable = false)
    public Role getRole() {
        return this.role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    @Column(name = "userName", unique = true, nullable = false)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "password", nullable = false)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "firstName")
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "lastName")
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "age", length = 50)
    public String getAge() {
        return this.age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    @Column(name = "email", unique = true)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "instagram_username")
    public String getInstagramUsername() {
        return this.instagramUsername;
    }

    public void setInstagramUsername(String instagramUsername) {
        this.instagramUsername = instagramUsername;
    }

    @Column(name = "discription")
    public String getDiscription() {
        return this.discription;
    }

    public void setDiscription(String discription) {
        this.discription = discription;
    }

    @Column(name = "allow_email_notification", nullable = false)
    public boolean isAllowEmailNotification() {
        return this.allowEmailNotification;
    }

    public void setAllowEmailNotification(boolean allowEmailNotification) {
        this.allowEmailNotification = allowEmailNotification;
    }

    @Column(name = "interest")
    public String getInterest() {
        return this.interest;
    }

    public void setInterest(String interest) {
        this.interest = interest;
    }

    @Column(name = "profileImage")
    public String getProfileImage() {
        return this.profileImage;
    }

    public void setProfileImage(String profileImage) {
        this.profileImage = profileImage;
    }

    /**
     * @return the createDate
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createDate", nullable = false, length = 8)
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * @param createDate the createDate to set
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}
